#!/bin/bash -e
# Usage ./smoke-test-runner [test-file] [extra-arguments]

top_srcdir=$(git rev-parse --show-toplevel)

export GJS_PATH="${top_srcdir}:${top_srcdir}/js${GJS_PATH:+:$GJS_PATH}"
export GI_TYPELIB_PATH="${top_srcdir}${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}"
export LD_LIBRARY_PATH="${top_srcdir}/.libs${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

if [ "$GJS_DEBUG_OUTPUT" == "" ]; then
    export GJS_DEBUG_OUTPUT=stderr
fi

if [ "$GJS_DEBUG_TOPICS" == "" ]; then
    export GJS_DEBUG_TOPICS="JS ERROR;JS LOG"
fi

DEBUG_COMMAND=""
if [ "$RUN_DEBUG" != "" ]; then
    DEBUG_COMMAND="gdb --args"
fi

exec $DEBUG_COMMAND gjs $@
