#!/bin/bash

input="$G_TEST_SRCDIR/autobahn/basic.yaml"
expected=${input/.yaml/-translated.json}
po=${input/.yaml/.po}
"$G_TEST_SRCDIR/../tools/autobahn" "$input" --translations "$po" | diff -u "$expected" -
