const blacklist = {
    "general-es": [
        "Abuso sexual",
        "Abuso y maltrato infantil",
        "Actores pornográficos de Alemania",
        "Actores pornográficos de Brasil",
        "Actores pornográficos de Canadá",
        "Actores pornográficos de Colombia",
        "Actores pornográficos de España",
        "Actores pornográficos de Estados Unidos",
        "Actores pornográficos de Francia",
        "Actores pornográficos de Hungría",
        "Actores pornográficos de Italia",
        "Actores pornográficos de Japón",
        "Actores pornográficos de México",
        "Actores pornográficos de Rumania",
        "Actores pornográficos del Reino Unido",
        "Actores pornográficos de la República Checa",
        "Altporn",
        "Anime y manga hentai",
        "Anime y manga lolicon",
        "Ano humano",
        "Aparato reproductor femenino",
        "Aparato reproductor masculino",
        "BDSM",
        "Cine pornográfico",
        "Erotismo anal",
        "Erotismo oral",
        "Estudios pornográficos",
        "Fetichismo sexual",
        "Géneros pornográficos",
        "Incesto",
        "Industria del sexo",
        "Jerga sexual",
        "Juguetes sexuales",
        "Leyendas urbanas sexuales",
        "Mama",
        "Masturbación",
        "Métodos de ejecución",
        "Modelos eróticas de Estados Unidos",
        "Novelas eróticas",
        "Nudismo",
        "Orgasmo",
        "Parafilias",
        "Pederastia",
        "Pene",
        "Penthouse Pets",
        "Piercing en los genitales",
        "Piercing en los genitales masculinos",
        "Pirsins",
        "Playboy",
        "Pornografía",
        "Prácticas sexuales",
        "Prostitución",
        "Relaciones íntimas",
        "Revistas para adultos",
        "Revolución sexual",
        "Sexo grupal",
        "Sexo ocasional",
        "Sitios web pornográficos",
        "Testículo",
        "Tortura"
    ],
    "general-pt": [
        "Anatomia sexual",
        "BDSM",
        "Estrelas pornográficas da Alemanha",
        "Estrelas pornográficas da Colômbia",
        "Estrelas pornográficas da Espanha",
        "Estrelas pornográficas da França",
        "Estrelas pornográficas da Hungria",
        "Estrelas pornográficas da Itália",
        "Estrelas pornográficas da Romênia",
        "Estrelas pornográficas da República Checa",
        "Estrelas pornográficas do Brasil",
        "Estrelas pornográficas do Canadá",
        "Estrelas pornográficas do Japão",
        "Estrelas pornográficas do México",
        "Estrelas pornográficas do Reino Unido",
        "Estrelas pornográficas dos Estados Unidos",
        "Fetichismo",
        "Hentai",
        "Indústria do sexo",
        "Mama",
        "Masturbação",
        "Métodos de execução",
        "Modificação corporal",
        "Nudez",
        "Objetos usados para estimulação sexual",
        "Orgasmo",
        "Parafilias",
        "Pederastia",
        "Pénis",
        "Playboy",
        "Pornografia",
        "Produtoras de filmes pornográficos",
        "Prostituição",
        "Relacionamentos íntimos",
        "Revistas de conteúdo adulto",
        "Sexo",
        "Sexualidade",
        "Sistema reprodutor",
        "Sistema reprodutor feminino",
        "Sistema reprodutor masculino",
        "Sites adultos",
        "Termos sexuais do Japão",
        "Tortura"
    ],
    "general-en": [
        "Alt porn",
        "American female adult models",
        "American pornographic actors",
        "Anal eroticism",
        "BDSM",
        "BDSM terminology",
        "Body piercing",
        "Brazilian pornographic film actors",
        "Breast",
        "British pornographic film actors",
        "Canadian pornographic film actors",
        "Casual sex",
        "Child abuse",
        "Clitoris",
        "Colombian pornographic film actors",
        "Czech pornographic film actors",
        "Erotica",
        "Erotica and pornography websites",
        "Execution methods",
        "Fellatio",
        "Female genital piercings",
        "French pornographic film actors",
        "Genital piercings",
        "German pornographic film actors",
        "Group sex",
        "Hentai",
        "Human female reproductive system",
        "Human male reproductive system",
        "Hungarian pornographic film actors",
        "Incest",
        "Intimate relationships",
        "Italian pornographic film actors",
        "Japanese pornographic film actors",
        "Japanese sex terms",
        "Male genital piercings",
        "Mammal female reproductive system",
        "Mammal male reproductive system",
        "Masturbation",
        "Mexican pornographic film actors",
        "Nudity",
        "Oral eroticism",
        "Orgasm",
        "Paraphilias",
        "Pederasty",
        "Penis",
        "Penthouse Pets",
        "Playboy",
        "Pornographic animation",
        "Pornographic film studios",
        "Pornographic magazines",
        "Pornography",
        "Pornography by genre",
        "Pornography portal",
        "Pornography terms",
        "Prostitution",
        "Romanian pornographic film actors",
        "Sex industry",
        "Sex positions",
        "Sex toys",
        "Sexual acts",
        "Sexual anatomy",
        "Sexual arousal",
        "Sexual fetishism",
        "Sexual revolution",
        "Sexual slang",
        "Sexual urban legends",
        "Spanish pornographic film actors",
        "Testicle",
        "Torture",
        "Vagina"
    ],
    "general-fr": [
        "Accessoire BDSM",
        "Acteur allemand de films pornographiques",
        "Acteur américain de films pornographiques",
        "Acteur brésilien de films pornographiques",
        "Acteur canadien de films pornographiques",
        "Acteur colombien de films pornographiques",
        "Acteur français de films pornographiques",
        "Acteur hongrois de films pornographiques",
        "Acteur italien de films pornographiques",
        "Acteur japonais de films pornographiques",
        "Acteur tchèque de films pornographiques",
        "Actrice espagnole de films pornographiques",
        "Actrice roumaine de films pornographiques",
        "Anatomie de l'appareil reproducteur masculin",
        "Anatomie sexuelle",
        "Appareil reproducteur féminin",
        "Appareil reproductif masculin",
        "Art érotique",
        "BDSM",
        "Cinéma pornographique",
        "Clitoris",
        "Érection",
        "Érotisme",
        "Érotisme anal",
        "Fétichisme sexuel",
        "Hentai manga",
        "Inceste",
        "Industrie du sexe",
        "Intimité",
        "Jouet sexuel",
        "Masturbation",
        "Méthode d'exécution",
        "Nudité",
        "Orgasme",
        "Paraphilie",
        "Pédérastie",
        "Pénis",
        "Penthouse Pets",
        "Piercing",
        "Playboy",
        "Pornographie",
        "Pornographie LGBT",
        "Position sexuelle",
        "Pratique sexuelle",
        "Pratique sexuelle en groupe",
        "Presse pornographique",
        "Prostitution",
        "Révolution sexuelle",
        "Sein",
        "Sexualité humaine",
        "Sexualité libre",
        "Site web érotique ou pornographique",
        "Société de production de films pornographiques",
        "Torture"
    ],
    "general-ar": [
        "العنف ضد الأطفال",
        "ممثلو أفلام إباحية ألمان",
        "ممثلو أفلام إباحية كنديون",
        "ممثلو أفلام إباحية أسبانيون",
        "ممثلو أفلام إباحية أمريكيون",
        "ممثلو أفلام إباحية فرنسيون",
        "ممثلو أفلام إباحية هنغاريون",
        "ممثلو أفلام إباحية إيطاليون",
        "ممثلو أفلام إباحية يابانيون",
        "جهاز تناسلي ذكري",
        "فتيشية",
        "صناعة الجنس",
        "ألعاب جنسية",
        "ثدي",
        "عري",
        "شذوذ جنسي",
        "قضيب",
        "بلاي بوي",
        "إباحة",
        "دعارة",
        "علاقات أليفة",
        "مواقع وب إباحية",
        "خصية",
        "طرق إعدام",
        "أوضاع جنسية",
        "تعذيب"
    ]
};
