#!/bin/bash -ex

APPDIR=$HOME/.local/share/applications
BINDIR=$HOME/.local/bin

if ! flatpak info --show-commit com.endlessm.Platform master; then
    flatpak install eos-runtimes com.endlessm.Platform master
fi
if ! flatpak info --show-commit com.endlessm.Sdk master; then
    flatpak install eos-runtimes com.endlessm.Sdk master
fi

mkdir -p $APPDIR
cat <<EOF > $APPDIR/ka-customizer.desktop
[Desktop Entry]
Name=KA Customizer
Terminal=false
Type=Application
Path=$BINDIR
Exec=$BINDIR/ka-customizer
Icon=system-run
StartupWMClass=KA Customizer
EOF

mkdir -p $BINDIR
wget -O $BINDIR/ka-customizer https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/ka-customizer
wget -O $BINDIR/ka-customizer-runner https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/ka-customizer-runner
chmod +x $BINDIR/ka-customizer-runner $BINDIR/ka-customizer

gdbus call --session \
    --dest org.gnome.Shell \
    --object-path /org/gnome/Shell \
    --method org.gnome.Shell.AppStore.AddApplication \
    ka-customizer.desktop
