#!/bin/bash -ex

APPDIR=$HOME/.local/share/applications
BINDIR=$HOME/.local/bin

for branch in master eos3.1; do
    if ! flatpak info --show-commit com.endlessm.Platform $branch; then
        flatpak install eos-runtimes com.endlessm.Platform $branch
    fi
    if ! flatpak info --show-commit com.endlessm.Sdk $branch; then
        flatpak install eos-runtimes com.endlessm.Sdk $branch
    fi
done

mkdir -p $APPDIR
cat <<EOF > $APPDIR/ka-customizer.desktop
[Desktop Entry]
Name=KA Customizer
Terminal=false
Type=Application
Path=$BINDIR
Exec=$BINDIR/ka-customizer
Icon=system-run
StartupWMClass=KA Customizer
EOF

mkdir -p $BINDIR
wget -O $BINDIR/ka-customizer https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/ka-customizer
wget -O $BINDIR/ka-customizer-runner https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/ka-customizer-runner
chmod +x $BINDIR/ka-customizer-runner $BINDIR/ka-customizer

gdbus call --session \
    --dest org.gnome.Shell \
    --object-path /org/gnome/Shell \
    --method org.gnome.Shell.AppStore.AddApplication \
    ka-customizer.desktop
