#!/bin/bash -ex

BRANCH=$1
shift

if [ "$1" = "update" ]; then
    shift
    flatpak update "com.endlessm.apps.Platform//$BRANCH"
    flatpak update "com.endlessm.apps.Sdk//$BRANCH"
    flatpak update "$1"
fi

# Host fs for files, use BRANCH runtime, --devel for scss and yaml tools
flatpak run --devel --filesystem=host --runtime="//$BRANCH" "$@"
