#!/bin/bash -ex

APPDIR=$HOME/.local/share/applications
BINDIR=$HOME/.local/bin

for branch in master 1; do
    if ! flatpak info --show-commit com.endlessm.apps.Platform $branch; then
        flatpak install eos-sdk com.endlessm.apps.Platform $branch
    fi
    if ! flatpak info --show-commit com.endlessm.apps.Sdk $branch; then
        flatpak install eos-sdk com.endlessm.apps.Sdk $branch
    fi
done

mkdir -p $APPDIR
cat <<EOF > $APPDIR/kactus.desktop
[Desktop Entry]
Name=Kactus
Terminal=false
Type=Application
Path=$BINDIR
Exec=$BINDIR/kactus
Icon=system-run
StartupWMClass=Kactus
EOF

mkdir -p $BINDIR
wget -O $BINDIR/kactus https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/kactus
wget -O $BINDIR/kactus-runner https://raw.githubusercontent.com/endlessm/eos-knowledge-lib/master/tools/kactus-runner
chmod +x $BINDIR/kactus-runner $BINDIR/kactus

gdbus call --session \
    --dest org.gnome.Shell \
    --object-path /org/gnome/Shell \
    --method org.gnome.Shell.AppStore.AddApplication \
    kactus.desktop
